In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
from scipy import stats

In [2]:
# Download historical BTC-USD data
btc = yf.download("BTC-USD", start="2020-01-01", interval="1d")

# Optional: Reset index if you want 'Date' as a column
btc.reset_index(inplace=True)

# Flatten the multi-index columns
btc.columns = btc.columns.droplevel(1)

YF.download() has changed argument auto_adjust default to True


[*********************100%***********************]  1 of 1 completed


In [3]:
btc['log-return'] = np.log(btc['Close']).diff()

In [8]:
btc_ret = btc['log-return'].dropna().values

In [9]:
btc_ret

array([-0.03027293,  0.05017175,  0.00891501, ..., -0.01250171,
        0.01311103, -0.00552977], shape=(1960,))

In [14]:
x = np.sort(btc_ret)
x

array([-0.46473018, -0.17405255, -0.15488955, ...,  0.13576426,
        0.16710432,  0.17182056], shape=(1960,))

In [15]:
order_x = np.argsort(btc_ret)
order_x

array([  70,  893, 1042, ...,  788,   77,  403], shape=(1960,))

In [17]:
# Step two, Compute intermediate value
z = np.array(pd.Series(x).rolling(2).mean().dropna())
z

array([-0.31939136, -0.16447105, -0.15149831, ...,  0.12780283,
        0.15143429,  0.16946244], shape=(1959,))

In [19]:
dv = abs(np.diff(btc_ret))
dv

array([0.08044467, 0.04125674, 0.00882587, ..., 0.00685073, 0.02561275,
       0.0186408 ], shape=(1959,))

In [23]:
# Step three, Compute trimmed mean, with pre-specified trim range
trimval = 0.1
dvtrim = stats.trim_mean(dv, trimval)
dvtrim

np.float64(0.028802705883321636)

In [25]:
# Step four, Compute upper limit and lower limit
xmin = x[0] - dvtrim
xmax = x[-1] + dvtrim

xmin, xmax

(np.float64(-0.49353288122309574), np.float64(0.2006232677714455))