# 3 เรื่องพื้นฐานของ PyTorch

เป็น framework ที่ได้รับความนิยมสำหรับสร้าง Deep Learning Model


In [59]:
import torch

## 1. Tensors
ตารางเก็บข้อมูลเชิงตัวเลข (Numerical)  ที่แต่ละ element มี index ในการระบุตำแหน่ง

Matrix

ลองมอง Matrix เหมือนแผนที่ ที่มีพิกัด Lattitude, Longtitude

$$
\begin{bmatrix}
(1, 1) & (1, 2) & (1, 3)\\
(2, 1) & (2, 2) & (2, 3)\\
(3, 1) & (3, 2) & (3, 3)\\
\end{bmatrix}
$$

เรามักจะเห็น Matrix ได้รูปร่างหน้าตาแบบนี้:
$$
\mathbf{A}  =
\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
$$

ตัวอย่างเช่น: 
$$\mathbf{A} =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}$$

### 1.1 Scalar (หน่วยเล็กสุดของ Tensor)

In [60]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [61]:
# number of dimensions
scalar.ndim 

0

In [62]:
scalar.shape

torch.Size([])

In [63]:
# Get tensor back as Python int
scalar.item()

7

### 1.2 Vector (Tensor 1 มิติ)

In [64]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [65]:
# number of dimensions
vector.ndim

1

In [66]:
vector.shape

torch.Size([2])

### 1.3 Matrix (Tensor 2 มิติ)

In [67]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])

matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [68]:
# number of dimensions
matrix.ndim

2

In [69]:
matrix.shape

torch.Size([2, 2])

### 1.4 Random matrix

In [70]:
# Create a random tensor of size (or shape)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1661, 0.9791, 0.4375, 0.2640],
        [0.1210, 0.5202, 0.2462, 0.1660],
        [0.3256, 0.8609, 0.1696, 0.7795]])

In [71]:
random_tensor.shape

torch.Size([3, 4])

## 2. Tensor DataType: ความจุของหน่วยข้อมูล

ข้อควรระวัง: ข้อมูล Tensor อยู่กันคนละ หน่วยความจุด จะทำการ operation กันไม่ได้

In [72]:
# Create tensor with dtype float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [73]:
float_16_tensor.dtype

torch.float16

In [74]:
# Create tensor with dtype float32 (Default)
float_32_tensor = torch.tensor([3.0, 6.0, 9.0])
float_32_tensor

tensor([3., 6., 9.])

In [75]:
float_32_tensor.dtype

torch.float32

In [76]:
res = float_32_tensor * float_16_tensor
res

tensor([ 9., 36., 81.])

In [77]:
res.dtype

torch.float32

In [78]:
res = float_32_tensor @ float_32_tensor
res

tensor(126.)

In [79]:
res.dtype

torch.float32

In [80]:
float_32_tensor @ float_16_tensor

RuntimeError: dot : expected both vectors to have same dtype, but found Float and Half

## 3. Tensor Devices: อุปกรณ์ประมวลข้อมูล

ข้อควรระวัง: ข้อมูล Tensor อยู่กันคนละ device จะทำการ operation กันไม่ได้

In [81]:
# Check gor GPU access with PyTorch
torch.cuda.is_available()

False

In [82]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [83]:
# Count number of devices
torch.cuda.device_count()

0

In [84]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device = 'cpu')

# Tensor is not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [85]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])